### ISSUE TITLE
Some necessary code for building maps has been commented out

### ISSUE THREAD

**Issue by WangJunHao01** [UMMobileRoboticsT19/MASLAM#1]
Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally

**Comment by wyhhhhhhhhh** [comment]
> Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally

Hello,could you run it.

**Comment by WangJunHao01** [comment]
> > Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally
> 
> Hello,could you run it.

Yes,I can run it now, no need for more help. Thank you.

**Comment by wyhhhhhhhhh** [comment]
> > > Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally
> > 
> > 
> > Hello,could you run it.
> 
> Yes,I can run it now, no need for more help. Thank you.

OK! It means nothing mistake about this project. But, could you tell me some detail about the common running the experiment.Thank you!

**Comment by WangJunHao01** [comment]
> > > > Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally
> > > 
> > > 
> > > Hello,could you run it.
> > 
> > 
> > Yes,I can run it now, no need for more help. Thank you.
> 
> OK! It means nothing mistake about this project. But, could you tell me some detail about the common running the experiment.Thank you!

Well, actually it does need me to change some setup files, but that's what my teammate do. So I'm sorry that I can't tell you the details.

**Comment by wyhhhhhhhhh** [comment]
Hello，I want to ask a question about compile error.When I run sh build.sh, a mistake happened.Do you konw how to solve it.
![Uploading 12a24c97749b3587484605b8df5fff17.png…]()

**Comment by wyhhhhhhhhh** [comment]
Hello，I want to ask a question about compile error.When I run sh build.sh, a mistake happened.Do you konw how to solve it:
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:112:5: error: 'mpLoopCloser' was not declared in this scope
     mpLoopCloser = new LoopClosing(mpMap, mpKeyFrameDatabase, mpVocabulary, mSensor!=MONOCULAR);
     ^~~~~~~~~~~~
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:112:5: note: suggested alternative: 'mptLoopClosing'
     mpLoopCloser = new LoopClosing(mpMap, mpKeyFrameDatabase, mpVocabulary, mSensor!=MONOCULAR);
     ^~~~~~~~~~~~
     mptLoopClosing
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc: In member function 'void ORB_SLAM2::System::Shutdown()':
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:322:5: error: 'mpLoopCloser' was not declared in this scope
     mpLoopCloser->RequestFinish();
     ^~~~~~~~~~~~
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:322:5: note: suggested alternative: 'mptLoopClosing'
     mpLoopCloser->RequestFinish();

**Comment by wyhhhhhhhhh** [comment]
> > > > > Some necessary code for building maps has been commented out, and it seems that this project cannot be used normally. Can you provide a project that can be used normally
> > > > 
> > > > 
> > > > Hello,could you run it.
> > > 
> > > 
> > > Yes,I can run it now, no need for more help. Thank you.
> > 
> > 
> > OK! It means nothing mistake about this project. But, could you tell me some detail about the common running the experiment.Thank you!
> 
> Well, actually it does need me to change some setup files, but that's what my teammate do. So I'm sorry that I can't tell you the details.

Hello，I want to ask a question about compile error.When I run sh build.sh, a mistake happened.Do you konw how to solve it:
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:112:5: error: 'mpLoopCloser' was not declared in this scope
mpLoopCloser = new LoopClosing(mpMap, mpKeyFrameDatabase, mpVocabulary, mSensor!=MONOCULAR);
^~~~~~~~~~~~
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:112:5: note: suggested alternative: 'mptLoopClosing'
mpLoopCloser = new LoopClosing(mpMap, mpKeyFrameDatabase, mpVocabulary, mSensor!=MONOCULAR);
^~~~~~~~~~~~
mptLoopClosing
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc: In member function 'void ORB_SLAM2::System::Shutdown()':
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:322:5: error: 'mpLoopCloser' was not declared in this scope
mpLoopCloser->RequestFinish();
^~~~~~~~~~~~
/home/pc/docker/cccslam/cslam_ws/src/ORB_SLAM2/src/System.cc:322:5: note: suggested alternative: 'mptLoopClosing'
mpLoopCloser->RequestFinish();

**Comment by WangJunHao01** [comment]
Sorry, I don't know.In fact our team change orb-slam2 to orb-slam3. Maybe you need to solve it by your self.

**Comment by wyhhhhhhhhh** [comment]
OK,Thank you.
